services:
  app:
    build: .
    container_name: press_python-server
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/press
    environment:
      - DATABASE_URL=postgresql://pguser:password@db:5432/press 
    depends_on:
      - db
      - redis
  db:
    container_name: press_bd
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    image: postgres:15

  redis:
    image: redis:7.2
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370
#     volumes:
#       - postgres_data:
      

# volumes:
#   postgres_data: