services:

  db:
    container_name: press_bd
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    image: postgres:15
    volumes:
      - ./bd_backup:/docker-entrypoint-initdb.d
      - ./bd_backup:/var/lib/postgresql/data
  
  redis:
    image: redis:7.2
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    container_name: press_app
    # command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    command: gunicorn src.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind=0.0.0.0:8000 
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/press
    environment:
      - DATABASE_URL=postgresql://pguser:password@db:5432/press 
    depends_on:
      - db
      - redis
  
  celery:
    build:
      context: .
    env_file:
      - .env
    container_name: celery_app
    command: celery --app=src.tasks.tasks:celery worker -l INFO
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env
    container_name: flower_app
    command: celery --app=src.tasks.tasks:celery flower
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555