services:

  db:
    container_name: db_app
    ports:
      - '5555:5432'
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    image: postgres:15

  redis:
    image: redis:7.2
    container_name: redis_app
    command: --port 5370
    expose:
      - 5370

  app:
    build:
      context: .
    container_name: press
    # command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    command: alembic upgrade head && chmod a+x docker/app.sh
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - .:/press
    environment:
      - DATABASE_URL=postgresql://pguser:password@db:5432/press 
    depends_on:
      - db
      - redis
  
  celery:
    build:
      context: .
    env_file:
      - .env
    container_name: celery_app
    command: ls && chmod a+x docker/celery.sh 'celery'
    depends_on:
      - redis

  flower:
    build:
      context: .
    env_file:
      - .env
    container_name: flower_app
    command: ls && chmod a+x docker/celery.sh 'flower'
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555