services:
  app:
    build: .
    container_name: press_python-server
    command: uvicorn src.main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/press
    environment:
      - DATABASE_URL=postgresql://pguser:password@db:5432/press 
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=password
      

volumes:
  postgres_data: